### PR TITLE
Add NASIS-domain derived data/ST_family_classes.rda

### PR DESCRIPTION
**Pull request by brownag**
First cut at adding family-level domain info from NASIS RE: @dylanbeaudette suggestions on #22

Addressing #9 

TODO:
 - [x] link class names / domains to chapter and page numbers/ranges parsed from SoilKnowledgeBase "featurelist"

### CODE REVIEW

**Review by dylanbeaudette — APPROVED** [review]
Perfect, thanks for doing this.

**Comment by brownag** [comment]
There is still room for improvement in the mapping of family classes to key names / page etc.

**Comment by dylanbeaudette** [comment]
> There is still room for improvement in the mapping of family classes to key names / page etc.

Is that enough to hold up this PR?

**Comment by brownag** [comment]
> > There is still room for improvement in the mapping of family classes to key names / page etc.
> 
> Is that enough to hold up this PR?

It was in that I had half-incorporated the mapping per the TODO in the PR description--but stopped working when I noticed that a) I wanted the accessory data to be more detailed and b) there were some improperly parsed keys in SKB resulting in bad page/description linkages.

Basically the core of the problem is NASIS domains are not 1:1 with family-level keys in ST. The domains sometimes lump together classes that are referred to by several different keys. And some class names have multiple "definitions" depending on soil type/key.

I haven't gone so far as to duplicate domain labels for where they are used multiple times, but that may be the ultimate solution.  I think I have now got the low hanging fruit for mineral versus organic specializations of e.g. reaction or mineralogy class.

The items I wanted fixed should be resolved now. 

If you don't mind please take a look at the `ST_family_classes` data set that now has activity class, terric/limnic mineralogy and proper descriptions/criteria for CEC activity and let me know if you see anything really odd.

The semi-hardcoded way this is built in `rebuild-R-package-data-objects.R` will be refined as part of a future issue related to streamlining building the internal R datasets.

**Comment by brownag** [comment]
|classname                                                |group              |name                                                             | chapter| page|
|:--------------------------------------------------------|:------------------|:----------------------------------------------------------------|-------:|----:|
|allitic                                                  |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|amorphic                                                 |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|carbonatic                                               |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|isotic                                                   |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|kaolinitic                                               |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|magnesic                                                 |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|ferrihydritic                                            |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|ferritic                                                 |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|ferruginous                                              |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|gibbsitic                                                |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|glassy                                                   |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|glauconitic                                              |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|gypsic                                                   |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|halloysitic                                              |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|hypergypsic                                              |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|illitic                                                  |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|micaceous                                                |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|mixed                                                    |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|not used                                                 |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|parasesquic                                              |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|sesquic                                                  |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|siliceous                                                |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|smectitic                                                |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|vermiculitic                                             |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|anhydritic                                               |Mineral Family     |Mineralogy Classes                                               |      17|  325|
|diatomaceous                                             |Organic Family     |Mineralogy Classes Applied Only to Limnic Subgroups              |      17|  332|
|marly                                                    |Organic Family     |Mineralogy Classes Applied Only to Limnic Subgroups              |      17|  332|
|coprogenous                                              |Organic Family     |Mineralogy Classes Applied Only to Limnic Subgroups              |      17|  332|
|ferrihumic                                               |Organic Family     |Mineralogy Classes Applied Only to Terric Subgroups              |      17|  332|
|ashy                                                     |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|ashy over clayey                                         |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|ashy over clayey-skeletal                                |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|ashy over loamy                                          |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|ashy over loamy-skeletal                                 |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|ashy over medial                                         |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|ashy over medial-skeletal                                |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|ashy over pumiceous or cindery                           |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|ashy over sandy or sandy-skeletal                        |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|ashy-pumiceous                                           |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|ashy-skeletal                                            |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|ashy-skeletal over clayey                                |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|ashy-skeletal over fragmental or cindery                 |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|ashy-skeletal over loamy-skeletal                        |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|ashy-skeletal over sandy or sandy-skeletal               |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|cindery                                                  |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|cindery over loamy                                       |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|cindery over medial                                      |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|cindery over medial-skeletal                             |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|clayey                                                   |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|clayey over coarse-gypseous                              |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|clayey over fine-gypseous                                |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|clayey over fragmental                                   |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|clayey over gypseous-skeletal                            |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|clayey over loamy                                        |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|clayey over loamy-skeletal                               |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|clayey over sandy or sandy-skeletal                      |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|clayey-skeletal                                          |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|clayey-skeletal over sandy or sandy-skeletal             |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|coarse-gypseous                                          |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|coarse-loamy                                             |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|coarse-loamy over clayey                                 |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|coarse-loamy over fragmental                             |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|coarse-loamy over sandy or sandy-skeletal                |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|coarse-silty                                             |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|coarse-silty over clayey                                 |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|coarse-silty over sandy or sandy-skeletal                |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|fine                                                     |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|fine-gypseous                                            |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|fine-loamy                                               |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|fine-loamy over clayey                                   |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|fine-loamy over fragmental                               |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|fine-loamy over sandy or sandy-skeletal                  |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|fine-silty                                               |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|fine-silty over clayey                                   |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|fine-silty over fragmental                               |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|fine-silty over sandy or sandy-skeletal                  |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|fragmental                                               |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|gypseous-skeletal                                        |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|hydrous                                                  |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|hydrous over clayey                                      |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|hydrous over clayey-skeletal                             |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|hydrous over fragmental                                  |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|hydrous over loamy                                       |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|hydrous over loamy-skeletal                              |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|hydrous over sandy or sandy-skeletal                     |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|hydrous-pumiceous                                        |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|hydrous-skeletal                                         |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|loamy                                                    |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|loamy over ashy or ashy-pumiceous                        |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|loamy over coarse-gypseous                               |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|loamy over fine-gypseous                                 |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|loamy over pumiceous or cindery                          |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|loamy over sandy or sandy-skeletal                       |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|loamy-skeletal                                           |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|loamy-skeletal over cindery                              |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|loamy-skeletal over clayey                               |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|loamy-skeletal over fragmental                           |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|loamy-skeletal over gypseous-skeletal                    |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|loamy-skeletal over sandy or sandy-skeletal              |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial                                                   |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial over ashy                                         |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial over ashy-pumiceous or ashy-skeletal              |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial over clayey                                       |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial over clayey-skeletal                              |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial over fragmental                                   |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial over hydrous                                      |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial over loamy                                        |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial over loamy-skeletal                               |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial over pumiceous or cindery                         |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial over sandy or sandy-skeletal                      |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial-pumiceous                                         |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial-skeletal                                          |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial-skeletal over fragmental or cindery               |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial-skeletal over loamy-skeletal                      |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|medial-skeletal over sandy or sandy-skeletal             |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|not used                                                 |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|pumiceous                                                |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|pumiceous or ashy-pumiceous over loamy                   |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|pumiceous or ashy-pumiceous over loamy-skeletal          |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|pumiceous or ashy-pumiceous over medial                  |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|pumiceous or ashy-pumiceous over medial-skeletal         |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|pumiceous or ashy-pumiceous over sandy or sandy-skeletal |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|sandy                                                    |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|sandy or sandy-skeletal                                  |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|sandy over clayey                                        |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|sandy over loamy                                         |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|sandy-skeletal                                           |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|sandy-skeletal over loamy                                |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|very-fine                                                |Mineral Family     |Key to the Particle-Size and Substitute Classes of Mineral Soils |      17|  319|
|acid                                                     |Mineral Family     |Calcareous and Reaction Classes of Mineral Soils                 |      17|  328|
|allic                                                    |Mineral Family     |Calcareous and Reaction Classes of Mineral Soils                 |      17|  328|
|calcareous                                               |Mineral Family     |Calcareous and Reaction Classes of Mineral Soils                 |      17|  328|
|nonacid                                                  |Mineral Family     |Calcareous and Reaction Classes of Mineral Soils                 |      17|  328|
|not used                                                 |Mineral Family     |Calcareous and Reaction Classes of Mineral Soils                 |      17|  328|
|dysic                                                    |Organic Family     |Reaction Classes for Organic Soils                               |      17|  332|
|euic                                                     |Organic Family     |Reaction Classes for Organic Soils                               |      17|  332|
|aeric                                                    |Mineral or Organic |Soil Moisture Subclasses                                         |      NA|   NA|
|anthraquic                                               |Mineral or Organic |Soil Moisture Subclasses                                         |      NA|   NA|
|aquic                                                    |Mineral or Organic |Soil Moisture Subclasses                                         |      NA|   NA|
|aridic (torric)                                          |Mineral or Organic |Soil Moisture Subclasses                                         |      NA|   NA|
|oxyaquic                                                 |Mineral or Organic |Soil Moisture Subclasses                                         |      NA|   NA|
|typic                                                    |Mineral or Organic |Soil Moisture Subclasses                                         |      NA|   NA|
|udic                                                     |Mineral or Organic |Soil Moisture Subclasses                                         |      NA|   NA|
|ustic                                                    |Mineral or Organic |Soil Moisture Subclasses                                         |      NA|   NA|
|xeric                                                    |Mineral or Organic |Soil Moisture Subclasses                                         |      NA|   NA|
|coated                                                   |Mineral or Organic |Other Family Classes                                             |      NA|   NA|
|cracked                                                  |Mineral or Organic |Other Family Classes                                             |      NA|   NA|
|micro                                                    |Mineral or Organic |Other Family Classes                                             |      NA|   NA|
|not used                                                 |Mineral or Organic |Other Family Classes                                             |      NA|   NA|
|ortstein                                                 |Mineral or Organic |Other Family Classes                                             |      NA|   NA|
|shallow                                                  |Mineral or Organic |Other Family Classes                                             |      NA|   NA|
|uncoated                                                 |Mineral or Organic |Other Family Classes                                             |      NA|   NA|
|frigid                                                   |Mineral Family     |Soil Temperature Classes                                         |      17|  329|
|hypergelic                                               |Mineral Family     |Soil Temperature Classes                                         |      17|  329|
|hyperthermic                                             |Mineral Family     |Soil Temperature Classes                                         |      17|  329|
|isofrigid                                                |Mineral Family     |Soil Temperature Classes                                         |      17|  329|
|isohyperthermic                                          |Mineral Family     |Soil Temperature Classes                                         |      17|  329|
|isomesic                                                 |Mineral Family     |Soil Temperature Classes                                         |      17|  329|
|isothermic                                               |Mineral Family     |Soil Temperature Classes                                         |      17|  329|
|mesic                                                    |Mineral Family     |Soil Temperature Classes                                         |      17|  329|
|not used                                                 |Mineral Family     |Soil Temperature Classes                                         |      17|  329|
|pergelic                                                 |Mineral Family     |Soil Temperature Classes                                         |      17|  329|
|subgelic                                                 |Mineral Family     |Soil Temperature Classes                                         |      17|  329|
|thermic                                                  |Mineral Family     |Soil Temperature Classes                                         |      17|  329|
|aquic                                                    |Mineral or Organic |Soil Moisture Regimes                                            |       3|   28|
|aridic (torric)                                          |Mineral or Organic |Soil Moisture Regimes                                            |       3|   28|
|peraquic                                                 |Mineral or Organic |Soil Moisture Regimes                                            |       3|   28|
|perudic                                                  |Mineral or Organic |Soil Moisture Regimes                                            |       3|   28|
|udic                                                     |Mineral or Organic |Soil Moisture Regimes                                            |       3|   28|
|ustic                                                    |Mineral or Organic |Soil Moisture Regimes                                            |       3|   28|
|xeric                                                    |Mineral or Organic |Soil Moisture Regimes                                            |       3|   28|
|not used                                                 |Mineral Family     |Cation-Exchange Activity Classes                                 |      17|  327|
|subactive                                                |Mineral Family     |Cation-Exchange Activity Classes                                 |      17|  327|
|semiactive                                               |Mineral Family     |Cation-Exchange Activity Classes                                 |      17|  327|
|active                                                   |Mineral Family     |Cation-Exchange Activity Classes                                 |      17|  327|
|superactive                                              |Mineral Family     |Cation-Exchange Activity Classes                                 |      17|  327|
|araric                                                   |Mineral Family     |Use of Human-Altered and Human-Transported Material Classes      |      17|  323|
|artifactic                                               |Mineral Family     |Use of Human-Altered and Human-Transported Material Classes      |      17|  323|
|ashifactic                                               |Mineral Family     |Use of Human-Altered and Human-Transported Material Classes      |      17|  323|
|asphaltic                                                |Mineral Family     |Use of Human-Altered and Human-Transported Material Classes      |      17|  323|
|combustic                                                |Mineral Family     |Use of Human-Altered and Human-Transported Material Classes      |      17|  323|
|concretic                                                |Mineral Family     |Use of Human-Altered and Human-Transported Material Classes      |      17|  323|
|dredgic                                                  |Mineral Family     |Use of Human-Altered and Human-Transported Material Classes      |      17|  323|
|gypsifactic                                              |Mineral Family     |Use of Human-Altered and Human-Transported Material Classes      |      17|  323|
|methanogenic                                             |Mineral Family     |Use of Human-Altered and Human-Transported Material Classes      |      17|  323|
|pauciartifactic                                          |Mineral Family     |Use of Human-Altered and Human-Transported Material Classes      |      17|  323|
|pyrocarbonic                                             |Mineral Family     |Use of Human-Altered and Human-Transported Material Classes      |      17|  323|
|spolic                                                   |Mineral Family     |Use of Human-Altered and Human-Transported Material Classes      |      17|  323|

**Pull request merged**
